name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        uses: railway-app/railway-cli@v3
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          command: up

